"""Support module for browser-cdp tests."""

from .test_logger import (
    LogLevel,
    TestStep,
    TestContext,
    TestLogger,
    JsonFormatter,
    ExceptionCapture,
    create_test_logger,
    get_default_logger,
    set_default_logger,
    log_info,
    log_error,
    log_warning,
    log_debug,
    log_action,
    log_assertion,
    capture_exceptions,
    pytest_configure,
    pytest_runtest_setup,
    pytest_runtest_teardown,
    pytest_runtest_call,
    pytest_exception_interact,
)

from .exception_handler import (
    ErrorCategory,
    ErrorSeverity,
    TestError,
    RetryStrategy,
    RetryConfig,
    RetryableOperation,
    with_retry,
    ErrorHandler,
    BrowserErrorClassifier,
    error_boundary,
    RETRY_CONFIGS,
    get_retry_config,
)

from .test_reporter import (
    TestResult,
    TestSuiteResult,
    TestReporter,
    generate_test_report,
)

__all__ = [
    # test_logger
    'LogLevel',
    'TestStep',
    'TestContext',
    'TestLogger',
    'JsonFormatter',
    'ExceptionCapture',
    'create_test_logger',
    'get_default_logger',
    'set_default_logger',
    'log_info',
    'log_error',
    'log_warning',
    'log_debug',
    'log_action',
    'log_assertion',
    'capture_exceptions',
    'pytest_configure',
    'pytest_runtest_setup',
    'pytest_runtest_teardown',
    'pytest_runtest_call',
    'pytest_exception_interact',
    # exception_handler
    'ErrorCategory',
    'ErrorSeverity',
    'TestError',
    'RetryStrategy',
    'RetryConfig',
    'RetryableOperation',
    'with_retry',
    'ErrorHandler',
    'BrowserErrorClassifier',
    'error_boundary',
    'RETRY_CONFIGS',
    'get_retry_config',
    # test_reporter
    'TestResult',
    'TestSuiteResult',
    'TestReporter',
    'generate_test_report',
]
